const COURSES=[
{id:"canine-obedience",name:"Canine Obedience Training",price:1500,weeks:12,symbol:"🐕",description:"Learn foundations for clear communication, everyday manners, and building a positive relationship with your dog.",topics:["Basic commands and cues","Leash manners and everyday routines","Positive reinforcement foundations"]},
{id:"pet-grooming",name:"Pet Grooming",price:1500,weeks:12,symbol:"✂",description:"Explore grooming routines, coat care, and calm, considerate handling for common pet-care situations.",topics:["Coat and skin care basics","Grooming tools and hygiene","Gentle handling and safety"]},
{id:"animal-behaviour",name:"Animal Behaviour",price:1500,weeks:12,symbol:"♡",description:"Build an introductory understanding of animal body language, behaviour, and welfare-aware responses.",topics:["Reading body language","Understanding common behaviours","Enrichment and welfare"]},
{id:"pet-business-management",name:"Pet Business Management",price:1500,weeks:12,symbol:"▣",description:"Explore the practical foundations of organising and managing a pet-care service.",topics:["Service planning","Customer care and communication","Basic business organisation"]},
{id:"puppy-care",name:"Puppy Care",price:750,weeks:6,symbol:"🐾",description:"Learn helpful basics for supporting a puppy's early routines, comfort, and wellbeing.",topics:["Daily care and routines","Socialisation basics","Health, safety, and preparation"]},
{id:"pet-first-aid",name:"Pet First Aid",price:750,weeks:6,symbol:"✚",description:"An introductory overview of pet first-aid awareness and how to respond responsibly in an emergency.",topics:["Recognising an emergency","Safety and handling basics","When and how to seek veterinary help"]},
{id:"dog-walking",name:"Dog Walking",price:750,weeks:6,symbol:"⌁",description:"Build practical awareness of safe, responsible walks and meeting dogs' everyday needs.",topics:["Leash and route safety","Reading dog signals","Responsible walking routines"]}
];
const money=n=>"R"+Math.round(n).toLocaleString("en-ZA");
function card(c){return `<article class="course-card"><span class="course-symbol" aria-hidden="true">${c.symbol}</span><h3>${c.name}</h3><p>${c.description}</p><div class="course-meta"><span>${c.weeks} weeks</span><span>${money(c.price)}</span></div><a class="text-link" href="course.html?course=${encodeURIComponent(c.id)}">View course details →</a></article>`}
document.querySelectorAll("[data-year]").forEach(e=>e.textContent=new Date().getFullYear());
const featured=document.querySelector("[data-featured-courses]");if(featured)featured.innerHTML=COURSES.slice(0,3).map(card).join("");
const all=document.querySelector("[data-all-courses]");if(all)all.innerHTML=COURSES.map(card).join("");
const toggle=document.querySelector(".menu-toggle"),nav=document.querySelector(".main-nav");if(toggle&&nav)toggle.addEventListener("click",()=>{const open=nav.classList.toggle("open");toggle.setAttribute("aria-expanded",String(open))});
const picker=document.querySelector("[data-course-picker]"),detail=document.querySelector("[data-course-detail]");
if(picker&&detail){picker.innerHTML=COURSES.map(c=>`<option value="${c.id}">${c.name}</option>`).join("");const wanted=new URLSearchParams(location.search).get("course");if(COURSES.some(c=>c.id===wanted))picker.value=wanted;function render(){const c=COURSES.find(x=>x.id===picker.value)||COURSES[0];detail.innerHTML=`<p class="eyebrow">Course overview</p><h2>${c.symbol} ${c.name}</h2><p>${c.description}</p><span class="detail-price">${money(c.price)} · ${c.weeks} weeks</span><h3>Topics covered</h3><ul>${c.topics.map(t=>`<li>${t}</li>`).join("")}</ul><a class="button" href="fees.html">Calculate fees</a>`}picker.addEventListener("change",render);render()}
const options=document.querySelector("[data-fee-options]");
if(options){options.innerHTML=COURSES.map(c=>`<label class="fee-option"><input type="checkbox" name="course" value="${c.id}"><span><strong>${c.name}</strong><small>${c.weeks} weeks</small></span><span class="price">${money(c.price)}</span></label>`).join("");function update(){const ids=[...options.querySelectorAll('input[name="course"]:checked')].map(i=>i.value),chosen=COURSES.filter(c=>ids.includes(c.id)),subtotal=chosen.reduce((s,c)=>s+c.price,0),count=chosen.length,rate=count>=4?.15:count===3?.10:count===2?.05:0,saving=Math.round(subtotal*rate);document.querySelector("[data-count]").textContent=count;document.querySelector("[data-subtotal]").textContent=money(subtotal);document.querySelector("[data-discount]").textContent=`${rate*100}% (${money(saving)})`;document.querySelector("[data-total]").textContent=money(subtotal-saving)}options.addEventListener("change",update);update()}
const form=document.querySelector("[data-contact-form]");if(form)form.addEventListener("submit",e=>{e.preventDefault();if(!form.reportValidity())return;document.querySelector("[data-form-feedback]").textContent="Thank you! This demo form validated successfully. No message has been sent.";form.reset()});
